### ISSUE TITLE
QM/MM calculations: pDynamo3 and ORCA 5.0.4 QCModelORCA () issue

### ISSUE THREAD

**Issue by arm22470** [pdynamo/pDynamo3#4]
Hello everybody!

I’ve been attempting to run QM/MM calculations with the newest version of pDynamo3 (python3) and ORCA 5_0_4 (Linux system) by following the ORCA manual instructions (page 390) and pDynamo’s wiki.
Setting up the qcmodel = QCModelOrca (options, command = ……) in such a manner leads to an error.

#############################
File "<stdin>", line 1, in <module>
TypeError: AttributableObject.__init__() got an unexpected keyword argument 'scratch'
>>> system.DefineQCModel (qcmodel, qcSelection=Selection(Qreg) )
Traceback (most recent call last):
File "<stdin>", line 1, in <module>

################################

The same happens with variations like qcmodel = pMolecule.QCModelOrca (options, command = ……)

The only way I’ve been successful in avoiding the error has been by using qcmodel = QCModelOrca.WithOptions (…) which ironically doesn’t allow the use of user defined options for the ORCA method.
Has something changed in the way QCMoldelORCA ( ) is used?
Any help would be greatly appreciated.

Example of my code:
# . Define Model
options= \
"""
! UKS BP86 SV(P) Def2/J RI SlowConv PAL8
%basis
NewECP Fe "SDD" end
end
%scf MaxIter 1000
end
"""
jobname = 'test_job'
qcmodel = QCModelORCA (options, scratch = './tmp', deleteJobFiles = False, \
command = '/home/user/orca/orca')
system.DefineQCModel (qcmodel, qcSelection=Selection(Qreg) )
system.Summary ()

**Comment by garantes** [comment]
Hi,

ORCA 5 has altered its input/output syntax, and pDynamo3 has not (yet)
been updated to reflected that. If you want to use QCModelOrca (options,
command = ...), then you will need to execute ORCA 4. 

If you have to stick with ORCA 5, you will have to use 
QCModelORCA.WithOptions ( keywords = [ " UKS ", " BP86 ", " SV(P) ", " Def2/J ", " RI ", " SlowConv ", " PAL8 " ] )
with spaces between the keywords and the quotation marks, and you
probably won't be able to use the ORCA input modifiers (%basis, etc).

Cheers,

Guilherme

--

Prof. Dr. Guilherme Menegon Arantes

Instituto de Química
Universidade de São Paulo
Av. Prof. Lineu Prestes, 748 
São Paulo          05508-000
Brasil
Fone: 55-11-30913848       Sala 915
http://gaznevada.iq.usp.br/
___________________________________

**Comment by arm22470** [comment]
Thanks for the reply!
Its good to know, but when testing with pDynamo 2 (1.9.0 - python2.7) and ORCA 5 all methods of setting up the QCModelORCA work. Perhaps its just something regarding Python 3?

**Comment by arm22470** [comment]
First off, congratulations @garantes on your recent publication on Cytochrome bc1.Managed to get everything working correctly between pDynamo3/Orca 6.0.1 (and 5). Here the variable "options1" can be modified with what ever is required for the QM model. I hope this helps. The format used was as follows:
------------------------------------------------------------------------------------------------------------------------------------
 # . Define QC Model
options1= \
"""
!UKS BP86 TZVP Def2/J RI D4 PAL4
%basis
NewECP Fe "SDD" end
     end
%scf MaxIter 1000
     end
"""

qcmodel = QCModelORCA.WithOptions(keywords = [options1], scratch="./tmp")
system.DefineQCModel ( qcmodel, qcSelection = Selection (Qreg) )
system.electronicState = ElectronicState.WithOptions ( charge = 0, multiplicity = 2 )

# . Define NB model.
nbModel = NBModelORCA.WithDefaults ()
system.DefineNBModel (nbModel)

**Comment by garantes** [comment]
Hi there! 

Thanks for the message and update on the ORCA input. 

Cheers,

Guilherme
